export const CREATE_EVENT = 'CREATE_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';
export const DELETE_ALL_EVENTS = 'DELETE_ALL_EVENTS';

export const ADD_OPERRATION_LOG = 'ADD_OPERRATION_LOG';
export const DELETE_ALL_OPERRATION_LOGS = 'DELETE_ALL_OPERRATION_LOGS';
